version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: resicomm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: